# Generated by Django 5.0.3 on 2024-03-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='image',
            new_name='file_url',
        ),
    ]
