# Generated by Django 5.0.3 on 2024-03-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_image_imagepost_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='caption',
        ),
    ]
